name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - linux/amd64
          - linux/arm64
          - windows/amd64
          - windows/arm64
          - darwin/amd64
          - darwin/arm64
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build binary
        env:
          ARCH: ${{ matrix.arch }}
        id: build
        run: |
          arch_pair=${ARCH%%/*}-${ARCH##*/}
          output_file="tconv-${arch_pair}"
          if [ "${ARCH%%/*}" = "windows" ]; then
            output_file="${output_file}.exe"
          fi
          CGO_ENABLED=0 GOARCH=${ARCH##*/} GOOS=${ARCH%%/*} go build -o ${output_file} ./cmd/main.go
          echo arch_pair=$arch_pair | tee -a $GITHUB_OUTPUT
          echo output_file=$output_file | tee -a $GITHUB_OUTPUT

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: tconv-binary-${{ steps.build.outputs.arch_pair }}
          path: ${{ steps.build.outputs.output_file }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: tconv-binary-*
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            tconv-linux-amd64
            tconv-linux-arm64
            tconv-windows-amd64.exe
            tconv-windows-arm64.exe
            tconv-darwin-amd64
            tconv-darwin-arm64
